# Generated by Django 3.0.1 on 2019-12-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRNLabCore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contact',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
