# Generated by Django 3.0.1 on 2019-12-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRNLabCore', '0003_auto_20191219_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Patient',
        ),
    ]
